spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://o-kr-amd2.017711.xyz:3306/exercise-yym?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: yym
    password: "7s2JchCpQCnWGn6N"
    driver-class-name: com.mysql.cj.jdbc.Driver


  # ?????QQ?????
  mail:
    host: smtp.qq.com
    username: 196254331@qq.com
    password: bpdtjyehgbbfbjaj  # QQ?????????????
    port: 587
    default-encoding: UTF-8
    protocol: smtp # SMTP邮件协议
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: o-kr-amd2.017711.xyz
      port: 16379
      database: 3
      password: "HhFi23U6gsI4hjTeosKC2x31sOPMIe6i"

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secretKey: "hVg1LcycfyZCJd0YPVujGKE1KtL7ntmHEHmXFAE10jcwPRopYiVAxQcaUxB4ZKFgDUCgBxY8ujMU4ZuNuhciAjPUmWG199ztEXwy"
  expiration: 12 #过期时间 小时

user:  #用户
  salt: #盐
    length: 16 #长度


knife4j:
  enable: true
  setting:
    language: zh_cn


tebi:
  endpoint: http://s3.tebi.io  # TEBI 提供的 S3 兼容端点
  access-key: Gn9E8D9S6revGzrk         # 访问密钥
  secret-key: bT0dPfVjdSoOkZLN0O5CWXiLn0U5yn4oVxxNouYp         # 密钥
  bucket-name: yym        # 桶名称
  region: sgb






# MyBatis-Plus??
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
